spin_manifest_version = "1"
authors = ["enejsimrajh <enej.simrajh@gmail.com>"]
description = "Backend service for the Hello world app"
name = "hello-world-svc"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "hello_world_svc"
source = "../../target/wasm32-wasi/release/hello_world_svc.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "npx nx build"
watch = ["src/**/*.rs", "Cargo.toml"]
