spin_manifest_version = "1"
authors = ["enejsimrajh <enej.simrajh@gmail.com>"]
description = "Hello World http application"
name = "hello-world-http"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "hello"
source = "hello/target/wasm32-wasi/debug/hello.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/hello"
[component.build]
command = "npx nx build"
workdir = "hello"
watch = ["src/**/*.rs", "Cargo.toml"]

[[component]]
id = "world"
source = "world/target/wasm32-wasi/debug/world.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/world"
[component.build]
command = "npx nx build"
workdir = "world"
watch = ["src/**/*.rs", "Cargo.toml"]
